#!/usr/bin/env python3
"""Validate provider error bodies against structured lm15 errors."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from lm15.providers import AnthropicLM, GeminiLM, OpenAILM  # noqa: E402

CASES_ROOT = ROOT / "errors" / "cases"
REPORT_DIR = ROOT / "reports"
JsonObject = dict[str, Any]


@dataclass(frozen=True)
class ErrorResult:
    case_id: str
    provider: str
    status: str
    reason: str | None = None
    expected: JsonObject | None = None
    actual: JsonObject | None = None


def provider_lm(provider: str):
    if provider == "openai":
        return OpenAILM(api_key="test")
    if provider == "anthropic":
        return AnthropicLM(api_key="test")
    if provider == "gemini":
        return GeminiLM(api_key="test")
    raise ValueError(f"unknown provider: {provider}")


def load_cases() -> list[JsonObject]:
    cases: list[JsonObject] = []
    for path in sorted(CASES_ROOT.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        cases.extend(payload.get("cases", []))
    return cases


def check_case(case: JsonObject) -> ErrorResult:
    case_id = str(case["id"])
    provider = str(case["provider"])
    expected = dict(case["expected"])
    body = case.get("body", "")
    body_text = body if isinstance(body, str) else json.dumps(body)
    try:
        err = provider_lm(provider).normalize_error(int(case["status"]), body_text)
        actual = {
            "class": type(err).__name__,
            "code": err.code,
            "provider": err.provider,
            "provider_code": err.provider_code,
            "status": err.status,
            "request_id": err.request_id,
        }
        actual = {k: v for k, v in actual.items() if v is not None}
    except Exception as exc:
        return ErrorResult(case_id, provider, "error", str(exc), expected=expected)

    for key, value in expected.items():
        if actual.get(key) != value:
            return ErrorResult(
                case_id,
                provider,
                "fail",
                f"{key}: expected {value!r}, got {actual.get(key)!r}",
                expected=expected,
                actual=actual,
            )
    return ErrorResult(case_id, provider, "pass", expected=expected, actual=actual)


def result_to_dict(result: ErrorResult) -> JsonObject:
    return {
        "id": result.case_id,
        "provider": result.provider,
        "status": result.status,
        "reason": result.reason,
        "expected": result.expected,
        "actual": result.actual,
    }


def write_markdown(results: list[ErrorResult], path: Path) -> None:
    counts: JsonObject = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1
    lines = [
        "# Error fixture conformance",
        "",
        "Generated by `conformance/check_error_fixtures.py`.",
        "",
        "## Summary",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status in ("pass", "fail", "error"):
        lines.append(f"| {status} | {counts.get(status, 0)} |")
    lines.extend(["", "## Cases", "", "| Case | Provider | Status | Reason |", "|---|---|---|---|"])
    for result in results:
        reason = (result.reason or "").replace("|", "\\|")
        lines.append(f"| `{result.case_id}` | {result.provider} | {result.status} | {reason} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", help="run only one case id")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--json", type=Path)
    parser.add_argument("--markdown", type=Path)
    args = parser.parse_args(argv)

    cases = load_cases()
    if args.case:
        cases = [case for case in cases if case.get("id") == args.case]
        if not cases:
            raise SystemExit(f"unknown case: {args.case}")

    results = [check_case(case) for case in cases]
    counts: JsonObject = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1

    REPORT_DIR.mkdir(exist_ok=True)
    json_path = args.json or REPORT_DIR / "error-fixtures.json"
    md_path = args.markdown or REPORT_DIR / "error-fixtures.md"
    json_path.write_text(json.dumps({"summary": counts, "total": len(results), "results": [result_to_dict(r) for r in results]}, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(results, md_path)

    print(f"error fixture conformance: {counts} / total={len(results)}")
    print(f"json: {json_path}")
    print(f"markdown: {md_path}")

    if args.strict and any(result.status != "pass" for result in results):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
