#!/usr/bin/env python3
"""Validate canonical JSON serde fixtures."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from conformance.sources import contract_path  # noqa: E402

# One copy: the serde vector is read from the lm15-contract checkout
# (serde/canonical.json), never from a mirror in this repo.
FIXTURE_PATH = contract_path("serde", "canonical.json")
REPORT_DIR = ROOT / "reports"
JsonObject = dict[str, Any]


@dataclass(frozen=True)
class SerdeResult:
    case_id: str
    kind: str
    check: str
    status: str
    reason: str | None = None


JsonToObj = Callable[[JsonObject], Any]
ObjToJson = Callable[[Any], JsonObject]

# One table: the vet shim's kind registry is the reference's serde surface
# (harness/PROTOCOL.md "Serde kinds"); a second copy here drifted once.
from lm15.vet import KIND_SERDE  # noqa: E402


def load_cases() -> list[JsonObject]:
    if not FIXTURE_PATH.exists():
        raise FileNotFoundError(
            f"serde vector not found at {FIXTURE_PATH}; check out lm15-contract "
            "next to this repo or set LM15_CONTRACT_DIR"
        )
    return list(json.loads(FIXTURE_PATH.read_text(encoding="utf-8")).get("cases", []))


def clean_json(value: Any) -> Any:
    if isinstance(value, dict):
        out = {k: clean_json(v) for k, v in value.items()}
        return {k: v for k, v in out.items() if v not in (None, "", [], {})}
    if isinstance(value, list):
        return [clean_json(v) for v in value]
    return value


def check_json_case(case: JsonObject) -> tuple[SerdeResult, Any | None]:
    case_id = str(case["id"])
    kind = str(case["kind"])
    value = case["value"]
    if kind not in KIND_SERDE:
        return SerdeResult(case_id, kind, "json", "error", f"unknown kind: {kind}"), None
    from_dict, to_dict = KIND_SERDE[kind]
    try:
        obj = from_dict(value)
        got = clean_json(to_dict(obj))
        expected = clean_json(value)
    except Exception as exc:
        return SerdeResult(case_id, kind, "json", "error", str(exc)), None
    if got != expected:
        return SerdeResult(case_id, kind, "json", "fail", f"expected {expected!r}, got {got!r}"), obj
    return SerdeResult(case_id, kind, "json", "pass"), obj


def result_to_dict(result: SerdeResult) -> JsonObject:
    return {
        "id": result.case_id,
        "kind": result.kind,
        "check": result.check,
        "status": result.status,
        "reason": result.reason,
    }


def write_markdown(results: list[SerdeResult], path: Path) -> None:
    counts: JsonObject = {}
    for result in results:
        key = f"{result.check}:{result.status}"
        counts[key] = counts.get(key, 0) + 1
    lines = [
        "# Serde fixture conformance",
        "",
        "Generated by `conformance/check_serde_fixtures.py`.",
        "",
        "## Summary",
        "",
        "| Check/status | Count |",
        "|---|---:|",
    ]
    for key in sorted(counts):
        lines.append(f"| {key} | {counts[key]} |")
    lines.extend(["", "## Cases", "", "| Case | Kind | Check | Status | Reason |", "|---|---|---|---|---|"])
    for result in results:
        reason = (result.reason or "").replace("|", "\\|")
        lines.append(f"| `{result.case_id}` | {result.kind} | {result.check} | {result.status} | {reason} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--json", type=Path)
    parser.add_argument("--markdown", type=Path)
    args = parser.parse_args(argv)

    results: list[SerdeResult] = []
    for case in load_cases():
        json_result, _obj = check_json_case(case)
        results.append(json_result)

    counts: JsonObject = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1

    REPORT_DIR.mkdir(exist_ok=True)
    json_path = args.json or REPORT_DIR / "serde-fixtures.json"
    md_path = args.markdown or REPORT_DIR / "serde-fixtures.md"
    json_path.write_text(json.dumps({"summary": counts, "total": len(results), "results": [result_to_dict(r) for r in results]}, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(results, md_path)

    print(f"serde fixture conformance: {counts} / total={len(results)}")
    print(f"json: {json_path}")
    print(f"markdown: {md_path}")

    if args.strict and any(result.status not in {"pass", "skip"} for result in results):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
