#!/usr/bin/env python3
"""Validate saved provider responses against canonical lm15 expectations."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from response_fixtures import (  # noqa: E402
    assert_expect_lm15,
    assert_no_stream_errors,
    body_path_for_expect,
    is_stream_case,
    iter_cases_with_expect_lm15,
    materialize_stream_fixture,
    parse_complete_fixture,
)

REPORT_DIR = ROOT / "reports"
JsonObject = dict[str, Any]


@dataclass(frozen=True)
class ResponseResult:
    case_id: str
    provider: str
    feature: str
    kind: str
    status: str
    reason: str | None = None
    body_path: str | None = None


def check_case(provider: str, feature: str, case: JsonObject) -> ResponseResult:
    case_id = f"{provider}.{feature}"
    stream = is_stream_case(case)
    kind = "stream" if stream else "complete"
    body_path = body_path_for_expect(provider, feature, case["expect_lm15"], stream=stream)
    if body_path is None:
        return ResponseResult(case_id, provider, feature, kind, "missing_body", "no saved body")

    try:
        if stream:
            response = materialize_stream_fixture(provider, feature, body_path=body_path)
        else:
            response = parse_complete_fixture(provider, feature, body_path=body_path)
        assert_expect_lm15(response, case["expect_lm15"])
        return ResponseResult(
            case_id,
            provider,
            feature,
            kind,
            "pass",
            body_path=str(body_path.relative_to(ROOT)),
        )
    except Exception as exc:
        return ResponseResult(
            case_id,
            provider,
            feature,
            kind,
            "fail",
            str(exc),
            str(body_path.relative_to(ROOT)),
        )


def result_to_dict(result: ResponseResult) -> JsonObject:
    return {
        "id": result.case_id,
        "provider": result.provider,
        "feature": result.feature,
        "kind": result.kind,
        "status": result.status,
        "reason": result.reason,
        "body_path": result.body_path,
    }


def write_markdown(results: list[ResponseResult], path: Path) -> None:
    counts: JsonObject = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1
    by_kind: JsonObject = {}
    for result in results:
        by_kind.setdefault(result.kind, {}).setdefault(result.status, 0)
        by_kind[result.kind][result.status] += 1

    lines = [
        "# Response fixture conformance",
        "",
        "Generated by `conformance/check_response_fixtures.py`.",
        "",
        "## Summary",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status in ("pass", "fail", "missing_body"):
        lines.append(f"| {status} | {counts.get(status, 0)} |")
    lines.extend(["", "## By kind", "", "| Kind | Pass | Fail | Missing body |", "|---|---:|---:|---:|"])
    for kind in sorted(by_kind):
        stats = by_kind[kind]
        lines.append(f"| {kind} | {stats.get('pass', 0)} | {stats.get('fail', 0)} | {stats.get('missing_body', 0)} |")
    lines.extend([
        "",
        "## Cases",
        "",
        "| Case | Kind | Status | Body | Reason |",
        "|---|---|---|---|---|",
    ])
    for result in results:
        reason = (result.reason or "").replace("|", "\\|")
        body = result.body_path or ""
        lines.append(f"| `{result.case_id}` | {result.kind} | {result.status} | `{body}` | {reason} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", help="run only one case id")
    parser.add_argument("--strict", action="store_true", help="exit non-zero on failures/gaps")
    parser.add_argument("--json", type=Path, help="write machine-readable report JSON")
    parser.add_argument("--markdown", type=Path, help="write markdown report")
    args = parser.parse_args(argv)

    items = list(iter_cases_with_expect_lm15())
    if args.case:
        items = [item for item in items if f"{item[0]}.{item[1]}" == args.case]
        if not items:
            raise SystemExit(f"unknown case: {args.case}")

    results = [check_case(provider, feature, case) for provider, feature, case in items]
    counts: JsonObject = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1

    REPORT_DIR.mkdir(exist_ok=True)
    json_path = args.json or REPORT_DIR / "response-fixtures.json"
    md_path = args.markdown or REPORT_DIR / "response-fixtures.md"
    report = {
        "summary": counts,
        "total": len(results),
        "results": [result_to_dict(result) for result in results],
    }
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(results, md_path)

    print(f"response fixture conformance: {counts} / total={len(results)}")
    print(f"json: {json_path}")
    print(f"markdown: {md_path}")

    if args.strict and any(result.status != "pass" for result in results):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
