#!/usr/bin/env python3
"""Validate canonical JSON serde fixtures."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from lm15 import serde  # noqa: E402

FIXTURE_PATH = ROOT / "serde" / "canonical.json"
REPORT_DIR = ROOT / "reports"
JsonObject = dict[str, Any]


@dataclass(frozen=True)
class SerdeResult:
    case_id: str
    kind: str
    check: str
    status: str
    reason: str | None = None


JsonToObj = Callable[[JsonObject], Any]
ObjToJson = Callable[[Any], JsonObject]

KIND_SERDE: dict[str, tuple[JsonToObj, ObjToJson]] = {
    "part": (serde.part_from_dict, serde.part_to_dict),
    "message": (serde.message_from_dict, serde.message_to_dict),
    "tool": (serde.tool_from_dict, serde.tool_to_dict),
    "tool_choice": (serde.tool_choice_from_dict, serde.tool_choice_to_dict),
    "reasoning": (serde.reasoning_from_dict, serde.reasoning_to_dict),
    "config": (serde.config_from_dict, serde.config_to_dict),
    "cache_config": (serde.cache_config_from_dict, serde.cache_config_to_dict),
    "continuation_state": (serde.continuation_from_dict, serde.continuation_to_dict),
    "error_detail": (serde.error_detail_from_dict, serde.error_detail_to_dict),
    "delta": (serde.delta_from_dict, serde.delta_to_dict),
    "usage": (serde.usage_from_dict, serde.usage_to_dict),
    "stream_event": (serde.stream_event_from_dict, serde.stream_event_to_dict),
    "request": (serde.request_from_dict, serde.request_to_dict),
    "response": (serde.response_from_dict, serde.response_to_dict),
    "model_info": (serde.model_info_from_dict, serde.model_info_to_dict),
    "audio_format": (serde.audio_format_from_dict, serde.audio_format_to_dict),
    "live_config": (serde.live_config_from_dict, serde.live_config_to_dict),
    "live_client_event": (serde.live_client_event_from_dict, serde.live_client_event_to_dict),
    "live_server_event": (serde.live_server_event_from_dict, serde.live_server_event_to_dict),
}


def load_cases() -> list[JsonObject]:
    return list(json.loads(FIXTURE_PATH.read_text()).get("cases", []))


def clean_json(value: Any) -> Any:
    if isinstance(value, dict):
        out = {k: clean_json(v) for k, v in value.items()}
        return {k: v for k, v in out.items() if v not in (None, "", [], {})}
    if isinstance(value, list):
        return [clean_json(v) for v in value]
    return value


def check_json_case(case: JsonObject) -> tuple[SerdeResult, Any | None]:
    case_id = str(case["id"])
    kind = str(case["kind"])
    value = case["value"]
    if kind not in KIND_SERDE:
        return SerdeResult(case_id, kind, "json", "error", f"unknown kind: {kind}"), None
    from_dict, to_dict = KIND_SERDE[kind]
    try:
        obj = from_dict(value)
        got = clean_json(to_dict(obj))
        expected = clean_json(value)
    except Exception as exc:
        return SerdeResult(case_id, kind, "json", "error", str(exc)), None
    if got != expected:
        return SerdeResult(case_id, kind, "json", "fail", f"expected {expected!r}, got {got!r}"), obj
    return SerdeResult(case_id, kind, "json", "pass"), obj


def result_to_dict(result: SerdeResult) -> JsonObject:
    return {
        "id": result.case_id,
        "kind": result.kind,
        "check": result.check,
        "status": result.status,
        "reason": result.reason,
    }


def write_markdown(results: list[SerdeResult], path: Path) -> None:
    counts: JsonObject = {}
    for result in results:
        key = f"{result.check}:{result.status}"
        counts[key] = counts.get(key, 0) + 1
    lines = [
        "# Serde fixture conformance",
        "",
        "Generated by `conformance/check_serde_fixtures.py`.",
        "",
        "## Summary",
        "",
        "| Check/status | Count |",
        "|---|---:|",
    ]
    for key in sorted(counts):
        lines.append(f"| {key} | {counts[key]} |")
    lines.extend(["", "## Cases", "", "| Case | Kind | Check | Status | Reason |", "|---|---|---|---|---|"])
    for result in results:
        reason = (result.reason or "").replace("|", "\\|")
        lines.append(f"| `{result.case_id}` | {result.kind} | {result.check} | {result.status} | {reason} |")
    path.write_text("\n".join(lines) + "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--json", type=Path)
    parser.add_argument("--markdown", type=Path)
    args = parser.parse_args(argv)

    results: list[SerdeResult] = []
    for case in load_cases():
        json_result, _obj = check_json_case(case)
        results.append(json_result)

    counts: JsonObject = {}
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1

    REPORT_DIR.mkdir(exist_ok=True)
    json_path = args.json or REPORT_DIR / "serde-fixtures.json"
    md_path = args.markdown or REPORT_DIR / "serde-fixtures.md"
    json_path.write_text(json.dumps({"summary": counts, "total": len(results), "results": [result_to_dict(r) for r in results]}, indent=2, sort_keys=True) + "\n")
    write_markdown(results, md_path)

    print(f"serde fixture conformance: {counts} / total={len(results)}")
    print(f"json: {json_path}")
    print(f"markdown: {md_path}")

    if args.strict and any(result.status not in {"pass", "skip"} for result in results):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
