#!/usr/bin/env python3
"""Audit provider documentation drift against the conformance feature inventory."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import yaml

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from conformance.sources import api_references_path  # noqa: E402

# One copy: the scraped reference pages are read from the contract's
# scrape directory (lm15-contract/scrapes/<provider>/pages/, refreshed by
# its update.sh), never from a snapshot in this repo.
DOC_ROOT = api_references_path()
FEATURES_PATH = ROOT / "provider_requests" / "features.yaml"
REPORT_DIR = ROOT / "reports"
JsonObject = dict[str, Any]


@dataclass(frozen=True)
class DocReport:
    provider: str
    documented_params: list[str]
    feature_keys: list[str]
    unmapped_params: list[str]
    todo_features: list[str]


def load_features() -> dict[str, Any]:
    return yaml.safe_load(FEATURES_PATH.read_text(encoding="utf-8"))


def extract_openai_params(text: str) -> list[str]:
    in_body = False
    params: list[str] = []
    for line in text.splitlines():
        if line.strip() == "### Body Parameters":
            in_body = True
            continue
        if in_body and line.startswith("### "):
            break
        if in_body:
            match = re.match(r"^- `([a-z_]+):", line)
            if match:
                params.append(match.group(1))
    return params


def extract_anthropic_params(text: str) -> list[str]:
    in_body = False
    params: list[str] = []
    for line in text.splitlines():
        if "Body" in line and line.startswith("#"):
            in_body = True
            continue
        if in_body and line.startswith("# "):
            break
        if in_body:
            match = re.match(r"^- `([a-z_]+):", line)
            if match:
                params.append(match.group(1))
    return params


def extract_gemini_params(text: str) -> list[str]:
    in_body = False
    params: list[str] = []
    for line in text.splitlines():
        if "Request body" in line and line.startswith("#"):
            in_body = True
            continue
        if in_body and line.startswith("#"):
            break
        if in_body:
            match = re.match(r"^`([a-zA-Z_\[\]]+)`\s+`", line)
            if match:
                params.append(match.group(1).rstrip("[]"))
    return params


PROVIDERS: dict[str, tuple[Path, Callable[[str], list[str]]]] = {
    "openai": (DOC_ROOT / "openai" / "pages" / "responses--create.md", extract_openai_params),
    "anthropic": (DOC_ROOT / "anthropic" / "pages" / "messages--create.md", extract_anthropic_params),
    "gemini": (DOC_ROOT / "gemini" / "pages" / "generate-content.md", extract_gemini_params),
}

# Always-on lm15 Request fields that don't get a separate feature entry.
IGNORE_PARAMS = {"model", "messages", "contents", "input"}


def _normalize(name: str) -> str:
    """snake_case canonical form for camelCase or PascalCase param names."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def report_provider(provider: str, features: dict[str, Any]) -> DocReport:
    doc_path, extract = PROVIDERS[provider]
    if not doc_path.exists():
        raise FileNotFoundError(
            f"scraped reference page not found at {doc_path}; check out lm15-contract "
            "next to this repo (and run its scrapes/<provider>/update.sh) "
            "or set LM15_API_REFERENCES"
        )
    text = doc_path.read_text(encoding="utf-8")
    params = extract(text)
    feature_keys = sorted(features.get(provider, {}).get("features", {}))
    feature_text_blob = " ".join(
        feature_keys
        + [
            str(info.get("description") or "")
            for info in features.get(provider, {}).get("features", {}).values()
        ]
    ).lower()
    unmapped: list[str] = []
    for param in params:
        normalized = _normalize(param)
        lowered = param.lower()
        if lowered in IGNORE_PARAMS or normalized in IGNORE_PARAMS:
            continue
        if lowered in feature_text_blob or normalized in feature_text_blob:
            continue
        unmapped.append(param)
    todo = [
        name
        for name, info in features.get(provider, {}).get("features", {}).items()
        if info.get("status") == "todo"
    ]
    return DocReport(provider, params, feature_keys, unmapped, todo)


def write_markdown(reports: list[DocReport], path: Path) -> None:
    lines = ["# Provider doc drift", "", "Generated by `conformance/check_doc_drift.py`.", ""]
    for report in reports:
        lines.append(f"## {report.provider}")
        lines.append("")
        lines.append(f"- Documented params: {len(report.documented_params)}")
        lines.append(f"- Feature inventory entries: {len(report.feature_keys)}")
        lines.append(f"- Todo features: {len(report.todo_features)}")
        if report.unmapped_params:
            lines.append("- Unmapped doc params:")
            for param in report.unmapped_params:
                lines.append(f"  - `{param}`")
        else:
            lines.append("- No unmapped doc params")
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def report_to_dict(report: DocReport) -> JsonObject:
    return {
        "provider": report.provider,
        "documented_params": report.documented_params,
        "feature_keys": report.feature_keys,
        "unmapped_params": report.unmapped_params,
        "todo_features": report.todo_features,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--strict", action="store_true", help="exit non-zero on unmapped params")
    parser.add_argument("--json", type=Path)
    parser.add_argument("--markdown", type=Path)
    args = parser.parse_args(argv)

    features = load_features()
    reports = [report_provider(provider, features) for provider in PROVIDERS]

    REPORT_DIR.mkdir(exist_ok=True)
    json_path = args.json or REPORT_DIR / "doc-drift.json"
    md_path = args.markdown or REPORT_DIR / "doc-drift.md"
    json_path.write_text(json.dumps([report_to_dict(r) for r in reports], indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown(reports, md_path)

    total_unmapped = sum(len(report.unmapped_params) for report in reports)
    print(f"doc drift: {total_unmapped} unmapped params")
    print(f"json: {json_path}")
    print(f"markdown: {md_path}")

    if args.strict and total_unmapped:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
