"""Constructor signatures for type checkers, generated from the dataclasses.

Many lm15 value types store a tuple (so a Request is immutable and hashable)
but accept any sequence, and sometimes one bare item, when constructed:
``Request(model, messages=[Message.user("hi")])``. A dataclass derives its
``__init__`` from its field annotations, so without help a type checker
rejects that list, although ``__post_init__`` accepts it.

For each type below, this tool writes an ``if TYPE_CHECKING:`` block holding
the ``__init__`` signature a type checker should see: the same parameters, in
the same order, with the same keyword-only markers, as the ``__init__`` the
dataclass generates at runtime; stored ``tuple[X, ...]`` widened to
``Sequence[X]``, stored mappings to ``Mapping``, and the bare-item forms
``__post_init__`` accepts listed in WIDER. Nothing changes at runtime: the
block is never executed, and the dataclass still generates ``__init__``.

    python tools/gen_init_signatures.py          # rewrite the blocks
    python tools/gen_init_signatures.py --check  # exit 1 if any is stale

tests/test_init_signatures.py runs the check, and also checks that every
dataclass whose ``__post_init__`` converts a field has a block here.
"""
from __future__ import annotations

import argparse
import dataclasses
import importlib
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# module -> classes that normalize an input in __post_init__.
TYPES: dict[str, tuple[str, ...]] = {
    "lm15.types": (
        "ToolCallPart", "ToolResultPart", "DataPart", "Message", "FunctionTool", "BuiltinTool",
        "ToolChoice", "Config", "Request", "TokenLogprob", "FileUploadRequest",
        "SpeechGenerationRequest",
        "FilePage", "CachePage", "BatchRequest", "ImageGenerationRequest",
        "ImageGenerationResponse", "VideoGenerationRequest", "LiveConfig",
        "LiveClientTurnEvent", "LiveClientToolResultEvent",
    ),
    "lm15.compat": ("OpenAIChatCompat", "AnthropicCompat"),
    "lm15.features": ("HostSpec",),  # AccessPolicy writes its own __init__
    "lm15.models": ("InferenceModelInfo", "ModelInfo"),
    "lm15.profiles": ("ProviderProfile",),
}

# Fields whose __post_init__ also takes one bare item (read from each
# __post_init__; the test cross-checks them by constructing the value).
WIDER: dict[tuple[str, str], str] = {
    ("Message", "parts"): "Part | Sequence[Part]",
    ("ToolChoice", "allowed"): "str | Sequence[str]",
    ("Config", "stop"): "str | Sequence[str]",
    ("Request", "messages"): "Message | Sequence[Message]",
    ("Request", "system"): "SystemContent | None",
    ("Request", "tools"): "Tool | Sequence[Tool]",
    ("TokenLogprob", "top"): "TopLogprob | Sequence[TopLogprob]",
    ("LiveConfig", "system"): "SystemContent | None",
    ("LiveConfig", "tools"): "Tool | Sequence[Tool]",
    ("LiveClientTurnEvent", "parts"): "PromptPart | Sequence[PromptPart]",
}

# JSON a caller writes: the stored type is the recursive JSON alias, which no
# ordinary dict variable can match (dict is invariant), so the input is any
# dict, or any value; __post_init__ checks that the contents are JSON.
JSON_INPUT = {"JsonObject": "dict[str, Any]", "Extensions": "dict[str, Any]",
              "ProviderData": "dict[str, Any]", "JsonValue": "object"}

BEGIN = "# BEGIN generated by tools/gen_init_signatures.py: do not edit"
END = "# END generated"


def _split_top(text: str, sep: str) -> list[str]:
    """Split on ``sep`` outside brackets."""
    out, depth, start = [], 0, 0
    for i, ch in enumerate(text):
        depth += ch in "[("
        depth -= ch in "])"
        if depth == 0 and text.startswith(sep, i):
            out.append(text[start:i].strip())
            start = i + len(sep)
    out.append(text[start:].strip())
    return out


def _widen_one(annotation: str) -> str:
    """``tuple[X, ...]`` -> ``Sequence[X]``; ``dict[K, V]``/``Mapping[K, V]`` -> ``Mapping[K, V]`` (inner types too)."""
    m = re.fullmatch(r"tuple\[(.*), \.\.\.\]", annotation)
    if m:
        return f"Sequence[{_widen(m.group(1))}]"
    m = re.fullmatch(r"(?:dict|Mapping)\[(.*)\]", annotation)
    if m:
        return f"Mapping[{', '.join(_widen(a) for a in _split_top(m.group(1), ','))}]"
    m = re.fullmatch(r"tuple\[(.*)\]", annotation)
    if m:
        return f"tuple[{', '.join(_widen(a) for a in _split_top(m.group(1), ','))}]"
    return annotation


def _widen(annotation: str) -> str:
    return " | ".join(_widen_one(a) for a in _split_top(annotation, "|"))


def converted(cls: type) -> set[str]:
    """The fields ``__post_init__`` stores a normalized value into: widened only these."""
    source = inspect.getsource(cls.__post_init__)
    names = {f.name for f in dataclasses.fields(cls)
             if f'"{f.name}"' in source or f"_is_json_value(self.{f.name})" in source}
    if "_validate_continuation_field(self" in source:
        names.add("continuation")
    return names


def signature(cls: type) -> str:
    if _hand_written(cls):
        raise SystemExit(f"{cls.__name__} writes its own __init__: annotate that one; do not list it here")
    params: list[str] = ["self"]
    keyword: list[str] = []
    widened = converted(cls)
    # As dataclasses do: keyword-only fields move after all the others.
    for f in dataclasses.fields(cls):
        if not f.init:
            continue
        annotation = f.type if isinstance(f.type, str) else f.type.__name__
        if f.name == "continuation" and f.name in widened:
            annotation = "ContinuationState | Sequence[ContinuationState]"
        elif f.name in widened and (cls.__name__, f.name) in WIDER:
            annotation = WIDER[(cls.__name__, f.name)]
        elif f.name in widened:
            annotation = " | ".join(JSON_INPUT.get(a, _widen_one(a)) for a in _split_top(annotation, "|"))
        has_default = f.default is not dataclasses.MISSING or f.default_factory is not dataclasses.MISSING
        (keyword if f.kw_only else params).append(f"{f.name}: {annotation}" + (" = ..." if has_default else ""))
    if keyword:
        params += ["*", *keyword]
    return f"def __init__({', '.join(params)}) -> None: ..."


def _hand_written(cls: type) -> bool:
    try:
        inspect.getsource(cls.__init__)
    except (OSError, TypeError):
        return False  # generated by dataclasses: no source file
    return True


def block(cls: type, indent: str) -> str:
    sig = signature(cls)
    lines = [f"{indent}{BEGIN}", f"{indent}if TYPE_CHECKING:"]
    body = indent + "    "
    if len(body) + len(sig) <= 100:
        lines.append(f"{body}{sig}")
    else:  # one parameter per line
        head, rest = sig.split("(", 1)
        inner, tail = rest.rsplit(")", 1)
        lines.append(f"{body}{head}(")
        lines += [f"{body}    {p}," for p in _split_top(inner, ",")]
        lines.append(f"{body}){tail}")
    lines.append(f"{indent}{END}")
    return "\n".join(lines) + "\n"


def rewrite(module_name: str, names: tuple[str, ...]) -> tuple[Path, str, str]:
    module = importlib.import_module(module_name)
    path = Path(module.__file__)
    original = path.read_text(encoding="utf-8")
    text = original
    for name in names:
        cls = getattr(module, name)
        m = re.search(rf"^class {name}\b.*?:\n", text, re.M)
        assert m, name
        body_start = m.end()
        nxt = re.search(r"^\S", text[body_start:], re.M)
        body_end = body_start + (nxt.start() if nxt else len(text[body_start:]))
        body = text[body_start:body_end]
        indent = "    "
        new_block = block(cls, indent)
        existing = re.search(rf"^{indent}{re.escape(BEGIN)}\n.*?^{indent}{re.escape(END)}\n", body, re.M | re.S)
        if existing:
            body = body[: existing.start()] + new_block + body[existing.end():]
        else:
            post = re.search(rf"^(?:{indent}@.*\n)*{indent}def __post_init__", body, re.M)
            assert post, f"{name}: no __post_init__"
            body = body[: post.start()] + new_block + "\n" + body[post.start():]
        text = text[:body_start] + body + text[body_end:]
    text = _ensure_imports(text)
    return path, original, text


def _ensure_imports(text: str) -> str:
    """TYPE_CHECKING, and Sequence/Mapping for the checker only (no runtime import cost)."""
    needed = [n for n in ("Sequence", "Mapping") if re.search(rf"\b{n}\[", text)]
    if "dict[str, Any]" in text and not re.search(r"^from typing import .*\bAny\b", text, re.M):
        m = re.search(r"^from typing import (.*)$", text, re.M)
        names = sorted({*(x.strip() for x in m.group(1).split(",")), "Any"}, key=lambda x: (x != "TYPE_CHECKING", x))
        text = text[: m.start()] + f"from typing import {', '.join(names)}" + text[m.end():]
    if not re.search(r"^from typing import .*\bTYPE_CHECKING\b", text, re.M):
        m = re.search(r"^from typing import (.*)$", text, re.M)
        if m:
            names = sorted({*(s.strip() for s in m.group(1).split(",")), "TYPE_CHECKING"}, key=lambda s: (s != "TYPE_CHECKING", s))
            text = text[: m.start()] + f"from typing import {', '.join(names)}" + text[m.end():]
        else:
            future = re.search(r"^from __future__ import annotations\n", text, re.M)
            text = text[: future.end()] + "\nfrom typing import TYPE_CHECKING\n" + text[future.end():]
    have = set()
    for m in re.finditer(r"^(?:from (?:typing|collections\.abc) import (.*)|    from collections\.abc import (.*))$", text, re.M):
        have |= {s.strip() for s in (m.group(1) or m.group(2)).split(",")}
    missing = [n for n in needed if n not in have]
    if missing:
        marker = "if TYPE_CHECKING:  # the generated __init__ signatures\n"
        if marker in text:
            m = re.search(re.escape(marker) + r"    from collections\.abc import (.*)\n", text)
            names = sorted({*(s.strip() for s in m.group(1).split(",")), *missing})
            text = text[: m.start()] + marker + f"    from collections.abc import {', '.join(names)}\n" + text[m.end():]
        else:
            last = list(re.finditer(r"^(?:from \S+ import [^(\n]*|from \S+ import \([^)]*\)|import \S+)\n", text, re.M))[-1]
            text = text[: last.end()] + f"\n{marker}    from collections.abc import {', '.join(missing)}\n" + text[last.end():]
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if a block is stale; write nothing")
    args = parser.parse_args()
    sys.path.insert(0, str(ROOT))
    stale = []
    for module_name, names in TYPES.items():
        path, original, text = rewrite(module_name, names)
        if text != original:
            stale.append(path.relative_to(ROOT))
            if not args.check:
                path.write_text(text, encoding="utf-8")
    if args.check and stale:
        print("stale __init__ signatures in: " + ", ".join(map(str, stale)) + "; run python tools/gen_init_signatures.py")
        return 1
    print(("rewrote " + ", ".join(map(str, stale))) if stale and not args.check else "init signatures up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
